{
 "title": "Setup monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"OptoBoard Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OptoBoard_Voltage_Setting[V]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"OptoBoard Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OptoBoard_Current_Setting[A]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Modules Cooling Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Cooling_Voltage_Setting[V]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Modules Cooling Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Cooling_Current_Setting[A]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Serial Modules Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Serial_Modules_Voltage_Setting[V]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Serial Modules Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Serial_Modules_Current_Setting[A]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"OptoBoard Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OptoBoard_Status[On/Off]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Modules Cooling Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Cooling_Status[On/Off]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Serial Modules Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Serial_Modules_Status[On/Off]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Cooling_Voltage[V]\" or r[\"_field\"] == \"OptoBoard_Voltage[V]\" or r[\"_field\"] == \"Serial_Modules_Voltage[V]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Cooling_Current[A]\" or r[\"_field\"] == \"OptoBoard_Current[A]\" or r[\"_field\"] == \"Serial_Modules_Current[A]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"OUT_S10\")\n  |> filter(fn: (r) => r[\"Interlock\"] == \"Status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OUT_S10_C2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"OUT_S10\")\n  |> filter(fn: (r) => r[\"Interlock\"] == \"Status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OUT_S10_C1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"OUT_S10\")\n  |> filter(fn: (r) => r[\"Interlock\"] == \"Status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OUT_S10_C3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Module2 Temperature\" or r[\"_measurement\"] == \"Module1 Temperature\" or r[\"_measurement\"] == \"Environment Temperature\" or r[\"_measurement\"] == \"OptoBoard Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Environment_Temperature[*C]\" or r[\"_field\"] == \"Module1_Temperature[*C]\" or r[\"_field\"] == \"Module2_Temperature[*C]\" or r[\"_field\"] == \"OptoBoard_Temperature[*C]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Module2 Temperature\" or r[\"_measurement\"] == \"Module1 Temperature\" or r[\"_measurement\"] == \"Environment Temperature\" or r[\"_measurement\"] == \"OptoBoard Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Environment_Temperature[*C]\" or r[\"_field\"] == \"Module1_Temperature[*C]\" or r[\"_field\"] == \"Module2_Temperature[*C]\" or r[\"_field\"] == \"OptoBoard_Temperature[*C]\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}